// World Cup Penalty Data
// Update this file as new penalties are reviewed.
// x: horizontal goal placement, y: vertical goal placement (normalized 0=ground, 1=crossbar)
// Coordinate system assumed: x in meters from left post (0–7.32), y normalized 0–1
// Adjust GOAL_CONFIG.dataX/YMin/Max in app.js if the coordinate system differs.

const PENALTIES_DATA = [
  {
    id: 1, type: 'In-game', match: 'Switzerland vs. Qatar',
    date: '2026-06-13',
    taker: 'Breel Embolo', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.15282000601291656, y: 0.5645377710461617, xGOT: 0.86,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 2, type: 'In-game', match: 'Germany vs. Curaçao',
    date: '2026-06-14',
    taker: 'Kai Havertz', team: 'Germany',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.2536797970533371, y: 0.6290880814194679, xGOT: 0.85,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 3, type: 'In-game', match: 'England vs. Croatia',
    date: '2026-06-17',
    taker: 'Harry Kane', team: 'England',
    result: 'Scored on retake', outcome: 'Scored',
    stutter: false, techniqueNote: 'Review official retake only',
    timeTaken: null, x: 1.6455449163913727, y: 0.45582158118486404, xGOT: 0.63, // re-verify coords from FotMob
    keeper: 'Livakovic',
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 4, type: 'In-game', match: 'Austria vs. Jordan',
    date: '2026-06-17',
    taker: 'Marko Arnautović', team: 'Austria',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.39488351345062256, y: 0.43543729931116104, xGOT: 0.60,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 5, type: 'In-game', match: 'South Africa vs. Czechia',
    date: '2026-06-18',
    taker: 'Teboho Mokoena', team: 'South Africa',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.29402370750904083, y: 0.5424547865986824, xGOT: 0.75,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 6, type: 'In-game', match: 'Switzerland vs. Bosnia and Herzegovina',
    date: '2026-06-18',
    taker: 'Granit Xhaka', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.8472645580768585, y: 0.6494723930954933, xGOT: 0.92,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 7, type: 'In-game', match: 'Argentina vs. Austria',
    date: '2026-06-22',
    taker: 'Lionel Messi', team: 'Argentina',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: true, techniqueNote: 'Slow run-up, skip',
    timeTaken: 1.68, x: 2, y: 0.5199200684, xGOT: null, // missed target — FotMob shows "-" (xGOT only applies to on-target shots)
    keeper: 'Schlager',
    videoReviewed: true,
    url: 'https://www.youtube.com/watch?v=SllfQUDS6UU',
  },
  {
    id: 8, type: 'In-game', match: 'Norway vs. France',
    date: '2026-06-26',
    taker: 'Jørgen Strand Larsen', team: 'Norway',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: 2.66, x: 1.564814815, y: 0.5610916185, xGOT: 0.63,
    keeper: 'Mike Maignan',
    videoReviewed: true,
    url: 'https://www.youtube.com/watch?v=dSKETaGZ6Zc',
  },
  {
    id: 9, type: 'In-game', match: 'Egypt vs. Iran',
    date: '2026-06-26',
    taker: 'Mehdi Taremi', team: 'Iran',
    result: 'Saved', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: 0.95, x: 1.706018519, y: 0.669807853, xGOT: 0.85,
    keeper: 'Mostafa Shobeir',
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 10, type: 'In-game', match: 'Jordan vs. Argentina',
    date: '2026-06-27',
    taker: 'Lautaro Martínez', team: 'Argentina',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.3050132275132277, y: 0.35426622216931225, xGOT: 0.60,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 11, type: 'In-game', match: 'DR Congo vs. Uzbekistan',
    date: '2026-06-27',
    taker: 'Yoane Wissa', team: 'DR Congo',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.8069206774234772, y: 0.6392801776528358, xGOT: 0.90,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 12, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Kai Havertz', team: 'Germany',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: null, x: 1.282407407407408, y: 0.3351656937037037, xGOT: 0.99,
    keeper: 'Saved by Orlando Gill',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 13, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Maurício', team: 'Paraguay',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.717050264550264, y: 0.279523810952381, xGOT: 0.82,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 14, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Joshua Kimmich', team: 'Germany',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.26466931216931144, y: 0.47317460365079367, xGOT: 0.67,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 15, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Gustavo Gómez', team: 'Paraguay',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.3539550264550255, y: 0.537724867883598, xGOT: 0.79,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 16, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Jamal Musiala', team: 'Germany',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x:0.08312169312169392, y:0.537724867883598, xGOT: 0.81,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 17, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Matías Galarza', team: 'Paraguay',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.3251851851851839, y: 0.5479170148677249, xGOT: 0.79,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 18, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Nick Woltemade', team: 'Germany',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Slow, staggered run-up',
    timeTaken: null, x: 1.685847, y: 0.561092, xGOT: 0.69,
    keeper: 'Saved by Orlando Gill',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 19, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Nadiem Amiri', team: 'Germany',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.474987, y: 0.398432, xGOT: 0.84,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 20, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Antonio Sanabria', team: 'Paraguay',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.000000, y: 0.447921, xGOT: null,
    keeper: 'Just missed / wide',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 21, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Fabián Balbuena', team: 'Paraguay',
    result: 'Saved', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.544643, y: 0.561092, xGOT: 0.85,
    keeper: 'Verify exact touch/result on replay',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 22, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'Jonathan Tah', team: 'Germany',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.642400, y: 0.002751, xGOT: null,
    keeper: 'Over the bar',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 23, type: 'Shootout', match: 'Germany vs. Paraguay',
    date: '2026-06-29',
    taker: 'José Canale', team: 'Paraguay',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: 'Winning penalty',
    timeTaken: null, x: 1.353955, y: 0.075681, xGOT: 0.99,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760489/paraguay-germany',
  },
  {
    id: 24, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Teun Koopmeiners', team: 'Netherlands',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.737222, y: 0.547917, xGOT: 0.92,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 25, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Neil El Aynaoui', team: 'Morocco',
    result: 'Crossbar', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.435185, y: 0.019418, xGOT: null,
    keeper: 'Hit the crossbar',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 26, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Justin Kluivert', team: 'Netherlands',
    result: 'Post', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: null, x: 0.006349, y: 0.605258, xGOT: null,
    keeper: 'Hit the post',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 27, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Soufiane Rahimi', team: 'Morocco',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.325185, y: 0.495258, xGOT: 0.77,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 28, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Wout Weghorst', team: 'Netherlands',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.305013, y: 0.150423, xGOT: 0.99,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 29, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Chemsdine Talbi', team: 'Morocco',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.616190, y: 0.214974, xGOT: 0.93,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 30, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Quinten Timber', team: 'Netherlands',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.000000, y: 0.630616, xGOT: null,
    keeper: 'Missed wide',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 31, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Achraf Hakimi', team: 'Morocco',
    result: 'Post', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.015873, y: 0.625642, xGOT: null,
    keeper: 'Hit the post',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 32, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Crysencio Summerville', team: 'Netherlands',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: null, x: 0.435185, y: 0.206065, xGOT: 0.99,
    keeper: 'Saved by Yassine Bounou',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 33, type: 'Shootout', match: 'Netherlands vs. Morocco',
    date: '2026-06-29',
    taker: 'Ismael Saibari', team: 'Morocco',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: 'Winning penalty',
    timeTaken: null, x: 0.143638, y: 0.537725, xGOT: 0.86,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760488',
  },
  {
    id: 34, type: 'In-game', match: 'Belgium vs. Senegal',
    date: '2026-07-01',
    taker: 'Youri Tielemans', team: 'Belgium',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: 'Extra-time stoppage-time penalty',
    timeTaken: null, x: 1.8472645580768585, y: 0.24178648740053177, xGOT: 0.99,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 35, type: 'In-game', match: 'Portugal vs. Croatia',
    date: '2026-07-02',
    taker: 'Cristiano Ronaldo', team: 'Portugal',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.8790105283260345, y: 0.3589961901307106, xGOT: 0.92,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 36, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Mahmoud Saber', team: 'Egypt',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.083122, y: 0.269332, xGOT: 0.90,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 37, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Harry Souttar', team: 'Australia',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: true, techniqueNote: 'Slowed down in run-up',
    timeTaken: null, x: 1.501865, y: 0.002750, xGOT: null,
    keeper: 'Over the bar',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 38, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Ramy Rabia', team: 'Egypt',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.486561, y: 0.547917, xGOT: 0.84,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 39, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Jackson Irvine', team: 'Australia',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.575847, y: 0.160615, xGOT: 0.98,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 40, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Mohamed Salah', team: 'Egypt',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.990860, y: 0.321991, xGOT: 0.88,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 41, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Awer Mabil', team: 'Australia',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.091720, y: 0.527533, xGOT: 0.79,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 42, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Hossam Abdelmaguid', team: 'Egypt',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: 'Winning penalty',
    timeTaken: null, x: 0.305013, y: 0.451092, xGOT: 0.79,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 43, type: 'Shootout', match: 'Australia vs. Egypt',
    date: '2026-07-03',
    taker: 'Lucas Herrington', team: 'Australia',
    result: 'Crossbar', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.584987, y: 0.019418, xGOT: null,
    keeper: 'Hit the crossbar',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760499',
  },
  {
    id: 44, type: 'In-game', match: 'France vs. Paraguay',
    date: '2026-07-04',
    taker: 'Kylian Mbappé', team: 'France',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.5355026455026466, y: 0.5054497357671959, xGOT: 0.74,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 45, type: 'In-game', match: 'Brazil vs. Norway',
    date: '2026-07-05',
    taker: 'Bruno Guimarães', team: 'Brazil',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: 2.68, x: 1.564814815, y: 0.5407073246, xGOT: 0.63,
    keeper: 'Ørjan Nyland',
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 46, type: 'In-game', match: 'Mexico vs. England',
    date: '2026-07-05',
    taker: 'Harry Kane', team: 'England',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.21333590149879456, y: 0.4235463812947273, xGOT: 0.82,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 47, type: 'In-game', match: 'Mexico vs. England',
    date: '2026-07-05',
    taker: 'Raúl Jiménez', team: 'Mexico',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.4755713939666748, y: 0.6070050969719887, xGOT: 0.74,
    keeper: 'Pickford',
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 48, type: 'In-game', match: 'Brazil vs. Norway',
    date: '2026-07-05',
    taker: 'Neymar', team: 'Brazil',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.5043412744998932, y: 0.6171971932053566, xGOT: 0.75,
    keeper: 'Nyland',
    videoReviewed: true,
    url: 'https://www.statbunker.com/competitions/Penalties?comp_id=790',
  },
  {
    id: 49, type: 'In-game', match: 'Argentina vs. Egypt',
    date: '2026-07-07',
    taker: 'Lionel Messi', team: 'Argentina',
    result: 'Saved', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: 3.24, x: 1.383267196, y: 0.5084321924, xGOT: 0.64,
    keeper: 'Mostafa Shobeir',
    videoReviewed: true,
    url: 'https://www.youtube.com/watch?v=ziHTAgrzT8Q',
  },
  {
    id: 50, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Granit Xhaka', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.083122, y: 0.118148, xGOT: 0.99,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 51, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Juan Fernando Quintero', team: 'Colombia',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.587421, y: 0.289716, xGOT: 0.68,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 52, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Zeki Amdouni', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 1.575847, y: 0.451092, xGOT: 0.63,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 53, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Davinson Sánchez', team: 'Colombia',
    result: 'Crossbar', outcome: 'Failed',
    stutter: true, techniqueNote: 'Hesitates at beginning',
    timeTaken: null, x: 1.000000, y: 0.024974, xGOT: null,
    keeper: 'Crossbar/goal line, stayed out',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 54, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Manuel Akanji', team: 'Switzerland',
    result: 'Missed/off target', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation',
    timeTaken: null, x: 1.134616, y: 0.002751, xGOT: null,
    keeper: 'Over the bar',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 55, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Jaminton Campaz', team: 'Colombia',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.273267, y: 0.473175, xGOT: 0.76,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 56, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Cédric Itten', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.273267, y: 0.473175, xGOT: 0.93,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 57, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Juan Camilo "Cucho" Hernández', team: 'Colombia',
    result: 'Saved', outcome: 'Failed',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.394841, y: 0.411607, xGOT: 0.67,
    keeper: 'Saved by Gregor Kobel',
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 58, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Ruben Vargas', team: 'Switzerland',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 0.325185, y: 0.440899, xGOT: 0.61,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 59, type: 'Shootout', match: 'Switzerland vs. Colombia',
    date: '2026-07-07',
    taker: 'Luis Díaz', team: 'Colombia',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: null,
    timeTaken: null, x: 0.163810, y: 0.495258, xGOT: 0.80,
    keeper: null,
    videoReviewed: true,
    url: 'https://www.espn.com/soccer/match/_/gameId/760508',
  },
  {
    id: 60, type: 'In-game', match: 'France vs. Morocco',
    date: '2026-07-09',
    taker: 'Kylian Mbappé', team: 'France',
    result: 'Saved', outcome: 'Failed',
    stutter: true, techniqueNote: 'Stutter/hesitation; taken after long official delay',
    timeTaken: 3.13, x: 1.383267196, y: 0.5084321924, xGOT: 0.75,
    keeper: 'Yassine Bounou',
    videoReviewed: true,
    url: 'https://www.youtube.com/watch?v=vRsAcWceOBQ',
  },
  {
   id: 61, type: 'In-game', match: 'Spain vs. France',
    date: '2026-07-14',
    taker: 'Mikel Oyarzabal', team: 'Spain',
    result: 'Scored', outcome: 'Scored',
    stutter: false, techniqueNote: null,
    timeTaken: null, x: 1.737222, y: 0.225166, xGOT: 0.96,
    keeper: 'Maignan',
    videoReviewed: true,
    url: 'https://www.fotmob.com/matches/spain-vs-france/1hsydl?player=678234#4653855:tab=lineup'
  },
  {
   id: 62, type: 'In-game', match: 'England vs. France',
    date: '2026-07-18',
    taker: 'Bukayo Saka', team: 'England',
    result: 'Scored', outcome: 'Scored',
    stutter: true, techniqueNote: 'Stutter occurred before run-up',
    timeTaken: null, x: 1.737222, y: 0.483367, xGOT: 0.90,
    keeper: 'Maignan',
    videoReviewed: true,
    url: null
  }
];
