const PLAYER_DATA = {
  "Lionel Messi":               { position: "Forward",    age: 39, pk_scored: 89  },
  "Jørgen Strand Larsen":       { position: "Forward",    age: 26, pk_scored: 1   },
  "Mehdi Taremi":               { position: "Forward",    age: 34, pk_scored: 55  },
  "Bruno Guimarães":            { position: "Midfielder", age: 28, pk_scored: 3   },
  "Kylian Mbappé":              { position: "Forward",    age: 27, pk_scored: 51  },
  "Harry Kane":                 { position: "Forward",    age: 32, pk_scored: 81  },
  "Cristiano Ronaldo":          { position: "Forward",    age: 41, pk_scored: 160 },
  "Youri Tielemans":            { position: "Midfielder", age: 29, pk_scored: 21  },
  "Raúl Jiménez":               { position: "Forward",    age: 35, pk_scored: 29  },
  "Neymar":                     { position: "Forward",    age: 34, pk_scored: 69  },
  "Yoane Wissa":                { position: "Forward",    age: 29, pk_scored: 11  },
  "Marko Arnautović":           { position: "Forward",    age: 37, pk_scored: 12  },
  "Kai Havertz":                { position: "Forward",    age: 27, pk_scored: 14  },
  "Teboho Mokoena":             { position: "Midfielder", age: 29, pk_scored: 0   },
  "Granit Xhaka":               { position: "Midfielder", age: 33, pk_scored: 2   },
  "Breel Embolo":               { position: "Forward",    age: 29, pk_scored: 2   },
  "Lautaro Martínez":           { position: "Forward",    age: 28, pk_scored: 15  },
  "Maurício":                   { position: "Defense",    age: 38, pk_scored: 0   },
  "Joshua Kimmich":             { position: "Midfielder", age: 31, pk_scored: 5   },
  "Gustavo Gómez":              { position: "Defense",    age: 33, pk_scored: 11  },
  "Jamal Musiala":              { position: "Forward",    age: 23, pk_scored: 3   },
  "Matías Galarza":             { position: "Midfielder", age: 24, pk_scored: 0   },
  "Nick Woltemade":             { position: "Forward",    age: 24, pk_scored: 12  },
  "Nadiem Amiri":               { position: "Midfielder", age: 29, pk_scored: 15  },
  "Antonio Sanabria":           { position: "Forward",    age: 30, pk_scored: 7   },
  "Fabián Balbuena":            { position: "Defense",    age: 34, pk_scored: 0   },
  "Jonathan Tah":               { position: "Defense",    age: 30, pk_scored: 0   },
  "José Canale":                { position: "Defense",    age: 30, pk_scored: 0   },
  "Teun Koopmeiners":           { position: "Midfielder", age: 28, pk_scored: 33  },
  "Neil El Aynaoui":            { position: "Midfielder", age: 25, pk_scored: 3   },
  "Justin Kluivert":            { position: "Forward",    age: 27, pk_scored: 8   },
  "Soufiane Rahimi":            { position: "Forward",    age: 30, pk_scored: 12  },
  "Wout Weghorst":              { position: "Forward",    age: 33, pk_scored: 21  },
  "Chemsdine Talbi":            { position: "Forward",    age: 21,   pk_scored: 0   },
  "Quinten Timber":             { position: "Midfielder", age: 25, pk_scored: 3   },
  "Achraf Hakimi":              { position: "Defense",    age: 27, pk_scored: 0   },
  "Crysencio Summerville":      { position: "Forward",    age: 24, pk_scored: 6   },
  "Ismael Saibari":             { position: "Forward",    age: 25, pk_scored: 1   },
  "Mahmoud Saber":              { position: "Midfielder", age: 24, pk_scored: 1   },
  "Harry Souttar":              { position: "Defense",    age: 27, pk_scored: 0   },
  "Ramy Rabia":                 { position: "Defense",    age: 33, pk_scored: 3   },
  "Jackson Irvine":             { position: "Midfielder", age: 33, pk_scored: 0   },
  "Mohamed Salah":              { position: "Forward",    age: 34, pk_scored: 46  },
  "Awer Mabil":                 { position: "Forward",    age: 30, pk_scored: 4   },
  "Hossam Abdelmaguid":         { position: "Defense",    age: 25, pk_scored: 5   },
  "Lucas Herrington":           { position: "Defense",    age: 18, pk_scored: 0   },
  "Juan Fernando Quintero":     { position: "Forward",    age: 33, pk_scored: 18  },
  "Zeki Amdouni":               { position: "Forward",    age: 25, pk_scored: 6   },
  "Davinson Sánchez":           { position: "Defense",    age: 30, pk_scored: 0   },
  "Manuel Akanji":              { position: "Defense",    age: 31, pk_scored: 0   },
  "Jaminton Campaz":            { position: "Forward",    age: 26, pk_scored: 2   },
  "Cédric Itten":               { position: "Forward",    age: 29, pk_scored: 14  },
  'Juan Camilo "Cucho" Hernández': { position: "Forward", age: 27, pk_scored: 23  },
  "Ruben Vargas":               { position: "Forward",    age: 27, pk_scored: 1   },
  "Luis Díaz":                  { position: "Forward",    age: 29, pk_scored: 0   },
  "Mikel Oyarzabal":            { position: "Forward",    age: 29, pk_scored: 45  },
  "Bukayo Saka":                { position: "Forward",    age: 24, pk_scored: 15  },
};
